<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AssemblyName>ForceNames</AssemblyName>
		<RootNamespace>ForceNames</RootNamespace>
		<OutputType>Library</OutputType>
		<Platforms>AnyCPU</Platforms>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CounterStrikeSharp.API" Version="1.0.352">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="MySqlConnector" Version="2.5.0" />
	</ItemGroup>

	<Target Name="PruneReleaseOutput" AfterTargets="Build" Condition="'$(Configuration)'=='Release'">
		<ItemGroup>
			<FilesToKeep Include="$(OutputPath)ForceNames.dll" />
			<FilesToKeep Include="$(OutputPath)MySqlConnector.dll" />
			<FilesToKeep Include="$(OutputPath)ForceNames.pdb" />
			<FilesToKeep Include="$(OutputPath)ForceNames.deps.json" />
			<AllOutputFiles Include="$(OutputPath)**\*.*" />
			<ToDelete Include="@(AllOutputFiles)" Exclude="@(FilesToKeep)" />
		</ItemGroup>

		<Delete Files="@(ToDelete)" />
	</Target>
</Project>
